---
apiVersion: v1
kind: Pod
metadata:
  name: echoserver
  labels:
    app: echoserver
    comment: myfirstpod
    company: netology
    stage: study
  namespace: netology
spec:
  containers:
    - name: echoserver
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      resources:
        limits:
          memory: "128Mi"
          cpu: "1000m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
...