---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-view-bind
  namespace: netology
subjects:
  - kind: Group
    name: devs
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-view
  apiGroup: rbac.authorization.k8s.io
...